// Accessories generated by SSC Studio. Perks are registered in RegPerks.java.
package net.onixary.shapeShifterCurseFabric.studio;
import net.minecraft.util.Identifier;
import net.minecraft.text.Text;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
public final class StudioGenerated {
  public static void register() {
  }
}
